// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bukljfdhzsuqhwrvwcsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1a2xqZmRoenN1cWh3cnZ3Y3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NTIxNTIsImV4cCI6MjA4NzEyODE1Mn0.lihO16v4qlgx544I6lMOxCRnDBdY7aHYhjSoBm8uBrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});